#!/bin/sh /etc/rc.common

# Copyright (C) 2018 max0y <askmaxwork@gmail.com>
# Licensed to the public under the GNU General Public License v3.

START=65
STOP=15

EXTRA_COMMANDS="status"

run_cd8021x()
{
    local enable
    config_get_bool enable $1 enable
    
    if [ $enable ]; then
        local username
        local password
        local ifname
        local eap
        local cert
        local anonymous
        local phase2
        local pairwise 
        
        config_get username $1 username
        config_get password $1 password
        config_get ifname $1 ifname
        config_get eap $1 eap
        config_get cert $1 cert
        config_get anonymous $1 anonymous
        config_get phase2 $1 phase2
        config_get pairwise $1 pairwise
        
        
        killall wpa_supplicant
        
        echo -e "ctrl_interface=/var/run/wpa_supplicant\n" > /tmp/cd8021x.conf
        echo -e "ctrl_interface_group=root\n" >> /tmp/cd8021x.conf
        echo -e "eapol_version=2\n" >> /tmp/cd8021x.conf
        echo -e "ap_scan=0\n" >> /tmp/cd8021x.conf
        
        echo -e "network={\n" >> /tmp/cd8021x.conf
        echo -e "key_mgmt=IEEE8021X\n" >> /tmp/cd8021x.conf
        
        
        if [ ! -z "${eap// }" ]; then
          echo -e "eap=$eap\n" >> /tmp/cd8021x.conf
        fi
        
        if [ ! -z "${username// }" ]; then
          echo -e "identity=\"$username\"\n" >> /tmp/cd8021x.conf
        fi
        
        if [ ! -z "${password// }" ]; then
          echo -e "password=\"$password\"\n" >> /tmp/cd8021x.conf
        fi
        
        if [ ! -z "${cert// }" ]; then
          echo -e "ca_cert=\"$cert\"\n" >> /tmp/cd8021x.conf
        fi
        
        if [ ! -z "${anonymous// }" ]; then
          echo -e "anonymous_identity=\"$anonymous\"\n" >> /tmp/cd8021x.conf
        fi
        
        if [ ! -z "${phase2// }" ]; then
          echo -e "phase2=\"auth=$phase2\"\n" >> /tmp/cd8021x.conf 
        fi
        
        if [ ! -z "${pairwise// }" ]; then
          echo -e "pairwise=$pairwise\n" >> /tmp/cd8021x.conf 
        fi
        
        case "$eap" in
            "MD5")
                echo -e "eapol_flags=0\n" >> /tmp/cd8021x.conf
                ;;
            "PEAP")
                echo -e "eapol_flags=0\n" >> /tmp/cd8021x.conf
                ;;
            "MSCHAPV2")
                echo -e "eapol_flags=0\nphase1=\"peaplabel=1\"\n" >> /tmp/cd8021x.conf
                ;;             
            *)
        esac
        
        echo -e "}\n" >> /tmp/cd8021x.conf 

        wpa_supplicant -B -c /tmp/cd8021x.conf -i$ifname -Dwired -dd -t | tee /tmp/wpa_supplicant.log
        
        echo "cd802.1x client has started."
    else
      echo "cd802.1.x client not enabled"
    fi

}

start()
{
    config_load cd8021x
    config_foreach run_cd8021x login
}

stop()
{
    killall wpa_supplicant    
    echo "cd802.1x client has stopped."
}

status() {
	ps | grep wpa_supplicant
}

restart() {
	stop
	start
}

reload() {
	restart
}
