#!/bin/sh /etc/rc.common

# Copyright (C) 2018 max0y <askmaxwork@gmail.com>
# Licensed to the public under the GNU General Public License v3.

START=65

run_cd8021x()
{
    local enable
    config_get_bool enable $1 enable
    
    if [ $enable ]; then
        local username
        local password
        local ifname
        local eap
        local cert
        local anonymous
        local phase2
        local pairwise 
        
        config_get username $1 username
        config_get password $1 password
        config_get ifname $1 ifname
        config_get eap $1 eap
        config_get cert $1 cert
        config_get anonymous $1 anonymous
        config_get phase2 $1 phase2
        config_get pairwise $1 pairwise
        
        
        killall wpa_supplicant
        echo -e "ctrl_interface=/var/run/wpa_supplicant\nctrl_interface_group=root\neapol_version=2\nap_scan=0\nnetwork={\nkey_mgmt=IEEE8021X\neap=$eap\nca_cert=\"$cert\"\nidentity=\"$username\"\npassword=\"$password\"" > /tmp/cd8021x.conf
        
        if [ -z "${cert// }" ]; then
          echo -e "ca_cert=\"$cert\"\n" >> /tmp/cd8021x.conf
        fi
        
        if [ -z "${anonymous// }" ]; then
          echo -e "anonymous_identity=\"$anonymous\"\n" >> /tmp/cd8021x.conf
        fi
        
        if [ -z "${phase2// }" ]; then
          echo -e "phase2=\"auth=$phase2\"\n" >> /tmp/cd8021x.conf 
        fi
        
        if [ -z "${pairwise// }" ]; then
          echo -e "pairwise=$pairwise\n" >> /tmp/cd8021x.conf 
        fi
        
        case "$eap" in
            "MD5")
                echo -e "eapol_flags=0\n" >> /tmp/cd8021x.conf
                ;;
            "PEAP")
                echo -e "eapol_flags=0\n" >> /tmp/cd8021x.conf
                ;;
            "MSCHAPV2")
                echo -e "eapol_flags=0\nphase1=\"peaplabel=1\"\n" >> /tmp/cd8021x.conf
                ;;
            "PEAP/MSCHAPV2")
              
            *)
        esac
        
        echo -e "}" >> /tmp/cd8021x.conf 

        wpa_supplicant -B -c /tmp/cd8021x.conf -i$ifname -Dwired -dd -t -B | tee /tmp/wpa_supplicant.log
        
        echo "cd802.1x client has started."
    fi
}

start()
{
    if [ -f /tmp/cd8021x.conf ]; then
      rm /tmp/cd8021x.conf 
    fi
    config_load cd8021x
    config_foreach run_cd8021x login
}

stop()
{
    killall wpa_supplicant    
    echo "cd802.1x client has stoped."
}

status() {
	ps | grep wpa_supplicant
}

restart() {
	stop
	start
}

reload() {
	restart
}
